### ISSUE TITLE
Android端启动问题

### ISSUE THREAD

**Issue by Agape2077** [pymo/pymo#2]
似乎在Android7.0以上系统启动时会出现无法解压private.mp3的问题。。

**Comment by FireParadise** [comment]
"could not extract private data."
[https://github.com/pymo/pymo/blob/b646a4f72e6a412c24f1da99686754126888be28/android/pgs4a-0.9.6/src/org/renpy/android/PythonActivity.java](url)

**Comment by FireParadise** [comment]
> "could not extract private data."
> [https://github.com/pymo/pymo/blob/b646a4f72e6a412c24f1da99686754126888be28/android/pgs4a-0.9.6/src/org/renpy/android/PythonActivity.java](url)

好像pgs4a的作者没有适配新安卓的意思....6年没更新了

**Comment by pymo** [comment]
我用了这个repo的pgs4a更新了一下pymo，现在bug应该没有了
https://github.com/startgridsrc/pgs4a
